- ros_topic_name: "/@CURRENT_ROBOT@/odom"
  gz_topic_name: "/model/@CURRENT_ROBOT@/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/@CURRENT_ROBOT@/scan"
  gz_topic_name: "/model/@CURRENT_ROBOT@/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/@CURRENT_ROBOT@/imu"
  gz_topic_name: "/model/@CURRENT_ROBOT@/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/@CURRENT_ROBOT@/joint_states"
  gz_topic_name: "/model/@CURRENT_ROBOT@/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/@CURRENT_ROBOT@/cmd_vel"
  gz_topic_name: "/model/@CURRENT_ROBOT@/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ